import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "../utils/trpc";
import { Grid, Loading, Table, Text } from "@geist-ui/core";
import Card from "@geist-ui/core/esm/card/card";

const Home: NextPage = () => {
  const { data: PrepScores, isLoading } = trpc.scores?.prepScores.useQuery();
  const { data: SecScores } = trpc.scores?.secScores.useQuery();
  const dataprep = [
    { property: "", description: "", type: 'secondary | warning', default: '-' }
  ]
  const datasec = [
    { property: "", description: "", type: 'secondary | warning', default: '-' }
  ]


  if (isLoading) return <><Loading type="warning">Loading</Loading></>
  return (
    <>
      <Head>
        <title>تيناهتي 5 </title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta httpEquiv="refresh" content="20" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid.Container gap={2} justify="center" height="100px">
        <Grid xs={10}>
          <Text h1>اعدادي</Text>
        </Grid>
        <Grid xs={10}>
          <Text h1 >ثانوي</Text>
        </Grid>
        {PrepScores?.map(( score:any,index: any) => {
          dataprep.push({ property: score.points, description: score.name, type: 'secondary | warning', default: '-' })
          return <></>;
        })}
        {SecScores?.map(( score:any,index: any) => {
          datasec.push({ property: score.points, description: score.name, type: 'secondary | warning', default: '-' })
          return <></>;
        })}
        <Grid xs={10}>
                  <Table data={dataprep}>
                    <Table.Column prop="property" label="النقاط" />
                    <Table.Column prop="description" label="المجموعة" />
                  </Table>
                </Grid>
        <Grid xs={10}>
          <Table data={datasec}>
            <Table.Column prop="property" label="النقاط" />
            <Table.Column prop="description" label="المجموعة" />
          </Table>
        </Grid>

      </Grid.Container>


    </>
  );
};

export default Home;
